// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class ChatSenderInfo;
struct ChatSenderInfoDefaultTypeInternal;
extern ChatSenderInfoDefaultTypeInternal _ChatSenderInfo_default_instance_;
class PlayerInfo;
struct PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::ChatSenderInfo* Arena::CreateMaybeMessage<::Protocol::ChatSenderInfo>(Arena*);
template<> ::Protocol::PlayerInfo* Arena::CreateMaybeMessage<::Protocol::PlayerInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class PlayerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PlayerInfo) */ {
 public:
  inline PlayerInfo() : PlayerInfo(nullptr) {}
  ~PlayerInfo() override;
  explicit PROTOBUF_CONSTEXPR PlayerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerInfo(const PlayerInfo& from);
  PlayerInfo(PlayerInfo&& from) noexcept
    : PlayerInfo() {
    *this = ::std::move(from);
  }

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
               &_PlayerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerInfo& a, PlayerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerInfo& from) {
    PlayerInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PlayerInfo";
  }
  protected:
  explicit PlayerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIDFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
    kYawFieldNumber = 5,
    kStateFieldNumber = 6,
    kRoomFieldNumber = 7,
  };
  // uint64 Player_ID = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // float x = 2;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 3;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 4;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float yaw = 5;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // .Protocol.PlayerState state = 6;
  void clear_state();
  ::Protocol::PlayerState state() const;
  void set_state(::Protocol::PlayerState value);
  private:
  ::Protocol::PlayerState _internal_state() const;
  void _internal_set_state(::Protocol::PlayerState value);
  public:

  // .Protocol.RoomType room = 7;
  void clear_room();
  ::Protocol::RoomType room() const;
  void set_room(::Protocol::RoomType value);
  private:
  ::Protocol::RoomType _internal_room() const;
  void _internal_set_room(::Protocol::RoomType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PlayerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t player_id_;
    float x_;
    float y_;
    float z_;
    float yaw_;
    int state_;
    int room_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ChatSenderInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ChatSenderInfo) */ {
 public:
  inline ChatSenderInfo() : ChatSenderInfo(nullptr) {}
  ~ChatSenderInfo() override;
  explicit PROTOBUF_CONSTEXPR ChatSenderInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatSenderInfo(const ChatSenderInfo& from);
  ChatSenderInfo(ChatSenderInfo&& from) noexcept
    : ChatSenderInfo() {
    *this = ::std::move(from);
  }

  inline ChatSenderInfo& operator=(const ChatSenderInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatSenderInfo& operator=(ChatSenderInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatSenderInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatSenderInfo* internal_default_instance() {
    return reinterpret_cast<const ChatSenderInfo*>(
               &_ChatSenderInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ChatSenderInfo& a, ChatSenderInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatSenderInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatSenderInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatSenderInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatSenderInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatSenderInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatSenderInfo& from) {
    ChatSenderInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatSenderInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ChatSenderInfo";
  }
  protected:
  explicit ChatSenderInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSenderNameFieldNumber = 3,
    kPlayerIDFieldNumber = 1,
    kRoomFieldNumber = 2,
  };
  // string SenderName = 3;
  void clear_sendername();
  const std::string& sendername() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sendername(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sendername();
  PROTOBUF_NODISCARD std::string* release_sendername();
  void set_allocated_sendername(std::string* sendername);
  private:
  const std::string& _internal_sendername() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sendername(const std::string& value);
  std::string* _internal_mutable_sendername();
  public:

  // uint64 Player_ID = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // .Protocol.RoomType room = 2;
  void clear_room();
  ::Protocol::RoomType room() const;
  void set_room(::Protocol::RoomType value);
  private:
  ::Protocol::RoomType _internal_room() const;
  void _internal_set_room(::Protocol::RoomType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ChatSenderInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sendername_;
    uint64_t player_id_;
    int room_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerInfo

// uint64 Player_ID = 1;
inline void PlayerInfo::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t PlayerInfo::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t PlayerInfo::player_id() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.Player_ID)
  return _internal_player_id();
}
inline void PlayerInfo::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void PlayerInfo::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.Player_ID)
}

// float x = 2;
inline void PlayerInfo::clear_x() {
  _impl_.x_ = 0;
}
inline float PlayerInfo::_internal_x() const {
  return _impl_.x_;
}
inline float PlayerInfo::x() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.x)
  return _internal_x();
}
inline void PlayerInfo::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void PlayerInfo::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.x)
}

// float y = 3;
inline void PlayerInfo::clear_y() {
  _impl_.y_ = 0;
}
inline float PlayerInfo::_internal_y() const {
  return _impl_.y_;
}
inline float PlayerInfo::y() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.y)
  return _internal_y();
}
inline void PlayerInfo::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void PlayerInfo::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.y)
}

// float z = 4;
inline void PlayerInfo::clear_z() {
  _impl_.z_ = 0;
}
inline float PlayerInfo::_internal_z() const {
  return _impl_.z_;
}
inline float PlayerInfo::z() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.z)
  return _internal_z();
}
inline void PlayerInfo::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void PlayerInfo::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.z)
}

// float yaw = 5;
inline void PlayerInfo::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float PlayerInfo::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float PlayerInfo::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.yaw)
  return _internal_yaw();
}
inline void PlayerInfo::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void PlayerInfo::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.yaw)
}

// .Protocol.PlayerState state = 6;
inline void PlayerInfo::clear_state() {
  _impl_.state_ = 0;
}
inline ::Protocol::PlayerState PlayerInfo::_internal_state() const {
  return static_cast< ::Protocol::PlayerState >(_impl_.state_);
}
inline ::Protocol::PlayerState PlayerInfo::state() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.state)
  return _internal_state();
}
inline void PlayerInfo::_internal_set_state(::Protocol::PlayerState value) {
  
  _impl_.state_ = value;
}
inline void PlayerInfo::set_state(::Protocol::PlayerState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.state)
}

// .Protocol.RoomType room = 7;
inline void PlayerInfo::clear_room() {
  _impl_.room_ = 0;
}
inline ::Protocol::RoomType PlayerInfo::_internal_room() const {
  return static_cast< ::Protocol::RoomType >(_impl_.room_);
}
inline ::Protocol::RoomType PlayerInfo::room() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.room)
  return _internal_room();
}
inline void PlayerInfo::_internal_set_room(::Protocol::RoomType value) {
  
  _impl_.room_ = value;
}
inline void PlayerInfo::set_room(::Protocol::RoomType value) {
  _internal_set_room(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.room)
}

// -------------------------------------------------------------------

// ChatSenderInfo

// uint64 Player_ID = 1;
inline void ChatSenderInfo::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t ChatSenderInfo::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t ChatSenderInfo::player_id() const {
  // @@protoc_insertion_point(field_get:Protocol.ChatSenderInfo.Player_ID)
  return _internal_player_id();
}
inline void ChatSenderInfo::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void ChatSenderInfo::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:Protocol.ChatSenderInfo.Player_ID)
}

// .Protocol.RoomType room = 2;
inline void ChatSenderInfo::clear_room() {
  _impl_.room_ = 0;
}
inline ::Protocol::RoomType ChatSenderInfo::_internal_room() const {
  return static_cast< ::Protocol::RoomType >(_impl_.room_);
}
inline ::Protocol::RoomType ChatSenderInfo::room() const {
  // @@protoc_insertion_point(field_get:Protocol.ChatSenderInfo.room)
  return _internal_room();
}
inline void ChatSenderInfo::_internal_set_room(::Protocol::RoomType value) {
  
  _impl_.room_ = value;
}
inline void ChatSenderInfo::set_room(::Protocol::RoomType value) {
  _internal_set_room(value);
  // @@protoc_insertion_point(field_set:Protocol.ChatSenderInfo.room)
}

// string SenderName = 3;
inline void ChatSenderInfo::clear_sendername() {
  _impl_.sendername_.ClearToEmpty();
}
inline const std::string& ChatSenderInfo::sendername() const {
  // @@protoc_insertion_point(field_get:Protocol.ChatSenderInfo.SenderName)
  return _internal_sendername();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatSenderInfo::set_sendername(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sendername_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.ChatSenderInfo.SenderName)
}
inline std::string* ChatSenderInfo::mutable_sendername() {
  std::string* _s = _internal_mutable_sendername();
  // @@protoc_insertion_point(field_mutable:Protocol.ChatSenderInfo.SenderName)
  return _s;
}
inline const std::string& ChatSenderInfo::_internal_sendername() const {
  return _impl_.sendername_.Get();
}
inline void ChatSenderInfo::_internal_set_sendername(const std::string& value) {
  
  _impl_.sendername_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatSenderInfo::_internal_mutable_sendername() {
  
  return _impl_.sendername_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatSenderInfo::release_sendername() {
  // @@protoc_insertion_point(field_release:Protocol.ChatSenderInfo.SenderName)
  return _impl_.sendername_.Release();
}
inline void ChatSenderInfo::set_allocated_sendername(std::string* sendername) {
  if (sendername != nullptr) {
    
  } else {
    
  }
  _impl_.sendername_.SetAllocated(sendername, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sendername_.IsDefault()) {
    _impl_.sendername_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.ChatSenderInfo.SenderName)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
