# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nEnum.proto\x12\x08Protocol*\xde\x01\n\x0bPlayerState\x12\x15\n\x11PLAYER_STATE_NONE\x10\x00\x12\x15\n\x11PLAYER_STATE_WALK\x10\x01\x12\x14\n\x10PLAYER_STATE_RUN\x10\x02\x12\x15\n\x11PLAYER_STATE_JUMP\x10\x03\x12\x17\n\x13PLAYER_STATE_ATTACK\x10\x04\x12\x17\n\x13PLAYER_STATE_HITTED\x10\x05\x12\x15\n\x11PLAYER_STATE_STUN\x10\x06\x12\x14\n\x10PLAYER_STATE_DIE\x10\x07\x12\x15\n\x11PLAYER_STATE_DASH\x10\x08*0\n\x08RoomType\x12\x11\n\rROOM_TUTORIAL\x10\x00\x12\x11\n\rROOM_FIRSTDUN\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Enum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERSTATE._serialized_start=25
  _PLAYERSTATE._serialized_end=247
  _ROOMTYPE._serialized_start=249
  _ROOMTYPE._serialized_end=297
# @@protoc_insertion_point(module_scope)
