# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Enum_pb2 as Enum__pb2
import Struct_pb2 as Struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eProtocol.proto\x12\x08Protocol\x1a\nEnum.proto\x1a\x0cStruct.proto\"\x1d\n\x07\x43_LOGIN\x12\x12\n\nplayerName\x18\x01 \x01(\t\"E\n\x07S_LOGIN\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\ryourSessionID\x18\x02 \x01(\x04\x12\x12\n\nplayerName\x18\x03 \x01(\t\"F\n\x0c\x43_ENTER_ROOM\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.Protocol.PlayerInfo\x12\x12\n\nplayerName\x18\x02 \x01(\t\"2\n\x0cS_ENTER_ROOM\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.Protocol.PlayerInfo\"2\n\x0c\x43_LEAVE_ROOM\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.Protocol.PlayerInfo\"-\n\x07S_SPAWN\x12\"\n\x04Info\x18\x01 \x03(\x0b\x32\x14.Protocol.PlayerInfo\"\x1e\n\tS_DESPAWN\x12\x11\n\tPlayer_ID\x18\x01 \x01(\x04\">\n\x06\x43_MOVE\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.Protocol.PlayerInfo\x12\x10\n\x08\x64\x61shInfo\x18\x02 \x01(\x05\">\n\x06S_MOVE\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.Protocol.PlayerInfo\x12\x10\n\x08\x64\x61shInfo\x18\x02 \x01(\x05\"C\n\x06\x43_CHAT\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12,\n\nSenderInfo\x18\x02 \x01(\x0b\x32\x18.Protocol.ChatSenderInfo\"C\n\x06S_CHAT\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12,\n\nSenderInfo\x18\x02 \x01(\x0b\x32\x18.Protocol.ChatSenderInfo\"!\n\x0c\x43_DISCONNECT\x12\x11\n\tPlayer_ID\x18\x01 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _C_LOGIN._serialized_start=54
  _C_LOGIN._serialized_end=83
  _S_LOGIN._serialized_start=85
  _S_LOGIN._serialized_end=154
  _C_ENTER_ROOM._serialized_start=156
  _C_ENTER_ROOM._serialized_end=226
  _S_ENTER_ROOM._serialized_start=228
  _S_ENTER_ROOM._serialized_end=278
  _C_LEAVE_ROOM._serialized_start=280
  _C_LEAVE_ROOM._serialized_end=330
  _S_SPAWN._serialized_start=332
  _S_SPAWN._serialized_end=377
  _S_DESPAWN._serialized_start=379
  _S_DESPAWN._serialized_end=409
  _C_MOVE._serialized_start=411
  _C_MOVE._serialized_end=473
  _S_MOVE._serialized_start=475
  _S_MOVE._serialized_end=537
  _C_CHAT._serialized_start=539
  _C_CHAT._serialized_end=606
  _S_CHAT._serialized_start=608
  _S_CHAT._serialized_end=675
  _C_DISCONNECT._serialized_start=677
  _C_DISCONNECT._serialized_end=710
# @@protoc_insertion_point(module_scope)
