# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Struct.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Enum_pb2 as Enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cStruct.proto\x12\x08Protocol\x1a\nEnum.proto\"\x95\x01\n\nPlayerInfo\x12\x11\n\tPlayer_ID\x18\x01 \x01(\x04\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\x0b\n\x03yaw\x18\x05 \x01(\x02\x12$\n\x05state\x18\x06 \x01(\x0e\x32\x15.Protocol.PlayerState\x12 \n\x04room\x18\x07 \x01(\x0e\x32\x12.Protocol.RoomType\"Y\n\x0e\x43hatSenderInfo\x12\x11\n\tPlayer_ID\x18\x01 \x01(\x04\x12 \n\x04room\x18\x02 \x01(\x0e\x32\x12.Protocol.RoomType\x12\x12\n\nSenderName\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Struct_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERINFO._serialized_start=39
  _PLAYERINFO._serialized_end=188
  _CHATSENDERINFO._serialized_start=190
  _CHATSENDERINFO._serialized_end=279
# @@protoc_insertion_point(module_scope)
